version: 1.0.{build}
image: Visual Studio 2017
environment:
  nodejs_version: "7"
install:
- ps: >-
    Install-Product node $env:nodejs_version

    npm install yarn -g
build_script:
- ps: .\build.ps1 -target Build
